# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c153ffe3bbdacf470c0198c71cd53a46"
name = "customer-analytics"
handle = "customer-analytics-11"
application_url = "https://click-renewal-remark-took.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store00012312.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,read_fulfillments,read_orders,read_product_listings,read_products,write_checkouts,write_customers,write_fulfillments,write_orders,write_product_listings,write_products"

[auth]
redirect_urls = [
  "https://click-renewal-remark-took.trycloudflare.com/auth/callback",
  "https://click-renewal-remark-took.trycloudflare.com/auth/shopify/callback",
  "https://click-renewal-remark-took.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
